project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://eleafe.github.io/RR_Blog_2026/  # you must change this appropriately for RSS feeds to work properly
  title: "RR_Blog_2026"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand


